version: "3.7"


services:
#   oracle:
#     image: store/oracle/database-enterprise:12.2.0.1
#     environment:
#       # default "sys" user password mentioned in oracle image readme
#       SYS_PASSWORD: Oradoc_db1
#     ports:
#       - 1521:1521
#     #volumes:
#     #  - "./sql/oracle_setup.sql:/docker-entrypoint-initdb.d/oracle_setup.sql:z"

  postgres:
    # if you build image locally and tagged it as "postgres_oracle_fdw"
    #image: postgres_oracle_fdw

    # if you want to use prebuilt image
    #image: docker.io/toleg/postgres_oracle_fdw:14.4_fdw2.4.0
    image: galileo/postgres-oracle-fwd
    build:
      context: .
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./sql/postgres_oracle_setup.sql:/docker-entrypoint-initdb.d/postgres_oracle_setup.sql
    #depends_on:
    #  - oracle


